<a href="https://colab.research.google.com/github/gabriellim314/machine-learning-studies/blob/main/MLcourse_Topic1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

pd.set_option("display.max.columns", 100)
# to draw pictures in jupyter notebook
%matplotlib inline
# we don't like warnings
# you can comment the following 2 lines if you'd like to
import warnings

import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings("ignore")

In [2]:
# for Jupyter-book, we copy data from GitHub, locally, to save Internet traffic,
# you can specify the data/ folder from the root of your cloned
# https://github.com/Yorko/mlcourse.ai repo, to save Internet traffic
DATA_URL = "https://raw.githubusercontent.com/Yorko/mlcourse.ai/main/data/"

In [3]:
data = pd.read_csv(DATA_URL + "adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

1. How many men and women (sex feature) are represented in this dataset?

In [4]:
data["sex"].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

2. What is the average age (age feature) of women?

In [5]:
data[data["sex"] == "Female"]["age"].mean()

np.float64(36.85823043357163)

3. What is the percentage of German citizens (native-country feature)?

In [6]:
(data['native-country'] == 'Germany').mean() * 100

np.float64(0.42074874850281013)

4-5. What are the mean and standard deviation of age for those who earn more than 50K per year (salary feature) and those who earn less than 50K per year?

In [7]:
columns_to_show = ['age']

data.groupby(['salary'])[columns_to_show].agg(['mean', 'std'])

              age
             mean        std
salary
<=50K   36.783738  14.020088
>50K    44.249841  10.519028

6. Is it true that people who earn more than 50K have at least high school education? (education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters or Doctorate feature)

In [8]:
education_values = ['Bachelors', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', 'Masters', 'Doctorate',]

data.loc[data['salary'] == '>50K', 'education'].isin(education_values).all()

np.False_

The sentence is false.

7. Display age statistics for each race (race feature) and each gender (sex feature). Use groupby() and describe(). Find the maximum age of men of Amer-Indian-Eskimo race.

In [9]:
columns_to_show = ['age']

data.groupby(['sex', 'race'])[columns_to_show].agg(['mean', 'std', 'max'])

                                 age
                                mean        std max
sex    race
Female Amer-Indian-Eskimo  37.117647  13.114991  80
       Asian-Pac-Islander  35.089595  12.300845  75
       Black               37.854019  12.637197  90
       Other               31.678899  11.631599  74
       White               36.811618  14.329093  90
Male   Amer-Indian-Eskimo  37.208333  12.049563  82
       Asian-Pac-Islander  39.073593  12.883944  90
       Black               37.682600  12.882612  90
       Other               34.654321  11.355531  77
       White               39.652498  13.436029  90

Maximum age of men of Amer-Indian-Eskimo race: 82 years old

8. Among whom is the proportion of those who earn a lot (>50K) greater: married or single men (marital-status feature)? Consider as married those who have a marital-status starting with Married (Married-civ-spouse, Married-spouse-absent or Married-AF-spouse), the rest are considered bachelors.

In [15]:
# married men
data[(data["sex"] == "Male")
     & (data["marital-status"].str.startswith("Married"))][
    "salary"
].value_counts(normalize=True)

salary
<=50K    0.559486
>50K     0.440514
Name: proportion, dtype: float64

In [16]:
# single men
data[(data["sex"] == "Male")
     & (~data["marital-status"].str.startswith("Married"))][
    "salary"
].value_counts(normalize=True)

salary
<=50K    0.915505
>50K     0.084495
Name: proportion, dtype: float64

Married men earn a lot

9. What is the maximum number of hours a person works per week (hours-per-week feature)? How many people work such a number of hours, and what is the percentage of those who earn a lot (>50K) among them?

In [17]:
data['hours-per-week'].max()

99

In [27]:
(data['hours-per-week'] == 99).sum()

np.float64(29.411764705882355)

In [29]:
(data[data['hours-per-week'] == 99]['salary'] == '>50K'
).mean() * 100

np.float64(29.411764705882355)

10. Count the average time of work (hours-per-week) for those who earn a little and a lot (salary) for each country (native-country). What will these be for Japan?

In [25]:
pd.crosstab(
    data["native-country"],
    data["salary"],
    values=data["hours-per-week"],
    aggfunc=np.mean,
).T

native-country,?,Cambodia,Canada,China,Columbia,Cuba,Dominican-Republic,Ecuador,El-Salvador,England,France,Germany,Greece,Guatemala,Haiti,Holand-Netherlands,Honduras,Hong,Hungary,India,Iran,Ireland,Italy,Jamaica,Japan,Laos,Mexico,Nicaragua,Outlying-US(Guam-USVI-etc),Peru,Philippines,Poland,Portugal,Puerto-Rico,Scotland,South,Taiwan,Thailand,Trinadad&Tobago,United-States,Vietnam,Yugoslavia
salary,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
<=50K,40.164760,41.416667,37.914634,37.381818,38.684211,37.985714,42.338235,38.041667,36.030928,40.483333,41.058824,39.139785,41.809524,39.360656,36.325,40.0,34.333333,39.142857,31.3,38.233333,41.44,40.947368,39.625,38.239437,41.000000,40.375,40.003279,36.09375,41.857143,35.068966,38.065693,38.166667,41.939394,38.470588,39.444444,40.15625,33.774194,42.866667,37.058824,38.799127,37.193548,41.6
>50K,45.547945,40.000000,45.641026,38.900000,50.000000,42.440000,47.000000,48.750000,45.000000,44.533333,50.750000,44.977273,50.625000,36.666667,42.750,NaN,60.000000,45.000000,50.0,46.475000,47.50,48.000000,45.400,41.100000,47.958333,40.000,46.575758,37.50000,NaN,40.000000,43.032787,39.000000,41.500000,39.416667,46.666667,51.43750,46.800000,58.333333,40.000000,45.505369,39.200000,49.5